# Generated by Django 4.2.15 on 2024-09-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='hashtag',
            field=models.ManyToManyField(related_name='hash_product', to='products.hashtag'),
        ),
    ]
